# Generated by Django 4.2.7 on 2025-11-27 03:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('MINISTRY', 'Ministère de la Santé'), ('HEALTH_WORKER', 'Agent de Santé')], default='HEALTH_WORKER', help_text="Rôle de l'utilisateur dans le système", max_length=20, verbose_name='rôle')),
                ('badge_id', models.CharField(help_text='Identifiant unique du badge pour la connexion', max_length=50, unique=True, verbose_name='numéro de badge')),
                ('phone', models.CharField(help_text="Numéro de téléphone de l'utilisateur", max_length=20, verbose_name='numéro de téléphone')),
                ('health_center_id', models.PositiveIntegerField(blank=True, help_text="ID du centre de santé auquel est affecté l'agent", null=True, verbose_name='ID du centre de santé')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='adresse email')),
                ('is_active', models.BooleanField(default=True, help_text='Désignation si le compte est actif ou non', verbose_name='compte actif')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'utilisateur',
                'verbose_name_plural': 'utilisateurs',
                'ordering': ['last_name', 'first_name'],
                'permissions': [('view_dashboard', 'Peut voir le tableau de bord'), ('manage_users', 'Peut gérer les utilisateurs'), ('manage_health_centers', 'Peut gérer les centres de santé')],
            },
        ),
    ]
