# Generated by Django 4.2.7 on 2025-11-28 18:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('qr_codes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('city', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Mother',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=32)),
                ('birth_date', models.DateField()),
                ('profession', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('center', models.ForeignKey(blank=True, help_text='Centre principal de suivi de la mère', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mothers', to='mothers.healthcenter')),
                ('qr_card', models.OneToOneField(help_text='Carte QR utilisée par cette mère', on_delete=django.db.models.deletion.PROTECT, related_name='mother', to='qr_codes.qrcodecard')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
