# Generated by Django 4.2.7 on 2025-11-28 20:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mothers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreventionMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('vaccination', 'Vaccination'), ('prenatal', 'Prénatal'), ('nutrition', 'Nutrition'), ('info', 'Information'), ('urgence', 'Urgence')], default='info', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publié'), ('scheduled', 'Programmé')], default='draft', max_length=20)),
                ('target', models.CharField(choices=[('all', 'Tous'), ('mothers', 'Mères uniquement'), ('agents', 'Agents de santé')], default='all', max_length=20)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
