# Generated by Django 4.2.7 on 2025-11-28 20:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mothers', '0002_preventionmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_name', models.CharField(help_text='Prénom et nom du père', max_length=255, verbose_name='Nom du père')),
                ('father_phone', models.CharField(blank=True, max_length=32, verbose_name='Téléphone du père')),
                ('father_profession', models.CharField(blank=True, max_length=255, verbose_name='Profession du père')),
                ('pere_carnet_center', models.CharField(help_text='Nom du centre père-carnet CSD', max_length=255, verbose_name='Centre père-carnet CSD')),
                ('identification_code', models.CharField(help_text="Le code de l'identification de la maison", max_length=100, verbose_name="Code d'identification")),
                ('birth_center_name', models.CharField(blank=True, help_text="Si le centre n'est pas dans la liste", max_length=255, verbose_name='Nom du centre de naissance')),
                ('allocation_info', models.CharField(blank=True, help_text="Ils allocation l'femele", max_length=255, verbose_name="Information d'allocation")),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('birth_center', models.ForeignKey(blank=True, help_text='Centre de santé où la mère a accouché (optionnel)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='birth_records', to='mothers.healthcenter', verbose_name='Centre de naissance')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_records', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('mother', models.OneToOneField(help_text='Mère associée à ce carnet', on_delete=django.db.models.deletion.CASCADE, related_name='health_record', to='mothers.mother')),
            ],
            options={
                'verbose_name': 'Carnet de santé',
                'verbose_name_plural': 'Carnets de santé',
                'ordering': ('-created_at',),
            },
        ),
    ]
